TITLE ASSEMBLY-PROVA
.MODEL SMALL 
.DATA
    MSG DB 10,13,"PROVA 1 OSC. $"
.CODE
MAIN PROC 
    MOV AX, @DATA 
    MOV DS, AX
    MOV AH, 09
    MOV DX, OFFSET MSG 
    INT 21H
    MOV AH, 4ch
    INT 21H
MAIN ENDP
END MAIN 
