TITLE MACRO COPIA STRING
.MODEL SMALL
.STACK 0100H

PUSH_ALL  MACRO  
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX
    PUSH SI
    PUSH DI
ENDM
POP_ALL  MACRO  
    POP DI
    POP SI
    POP DX
    POP CX
    POP BX
    POP AX
ENDM
IMP_STR MACRO FONTE,QUANTIDADE
    LOCAL REPETE
    PUSH_ALL
    LEA SI, FONTE
    MOV AH,02
    MOV CX, QUANTIDADE
REPETE:
    MOV DL,[SI]
    INT 21H
    INC SI
    LOOP REPETE 
    POP_ALL
ENDM
COPIA_STR MACRO FONTE, DESTINO, QUANTIDADE
    LOCAL REPETE
    PUSH_ALL
     CLD
    LEA SI, FONTE
    LEA DI, DESTINO
    MOV CX, QUANTIDADE
;REPETE:
    REP MOVSB
    ;LOOP REPETE 
    POP_ALL
ENDM
INVERTE_STR MACRO FONTE, DESTINO, QUANTIDADE
    LOCAL REPETE
    PUSH_ALL
    CLD
    LEA SI, FONTE
    LEA DI, DESTINO
    ADD DI,7
    MOV CX, QUANTIDADE
REPETE:
    MOVSB
    SUB DI,2
    LOOP REPETE
    POP_ALL
ENDM
PULA_LINHA MACRO
    PUSH_ALL
    MOV AH,2
    MOV DL,10
    INT 21H
    POP_ALL
ENDM
INSERE_CAR MACRO STR1, CAR
	STD                        
	LEA     SI,STR2+7h        
    LEA     DI,STR2+8h     
    MOV     CX,5        
    REP    MOVSB     ; 
    LEA DI,STR2+3
    MOV AL, CAR
    STOSB
ENDM

.DATA
	STR1 DB 'OSC 2S24'
	STR2 DB  9 DUP(?)
    CAR EQU 'X'
	QTDE EQU 8
.CODE
MAIN PROC
	MOV AX,@DATA
	MOV DS,AX                ; inicializa DS
	MOV ES,AX                ; inicializa ES

    COPIA_STR STR1,STR2,QTDE
    IMP_STR STR2,8
    PULA_LINHA
    INSERE_CAR STR2,CAR
    IMP_STR STR2,9
    PULA_LINHA
    MOV AH,4CH
    INT 21H
MAIN ENDP
END MAIN